services:
  - type: cron
    name: booking-scraper-test
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
    startCommand: python booking_scraper_test.py
    schedule: "@manual"
